import 'package:get/get.dart';

class MyLocal implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "en": {
          "lanar": 'Arabic',
          "lanen": 'english',
          "appname": "𝓽𝓾𝓻𝓴𝓶𝓪𝓻𝓽",
          "splash1": "Welcome to 𝓽𝓾𝓻𝓴𝓶𝓪𝓻𝓽",
          "splash2": "We help people conect with stores \naround turkey",
          "splash3":
              "We show the easy way to shop. \nJust stay at home with us",
          "Letsshop": "Let’s shop!",
          'Login': 'Login',
          "Register": 'Register',
          "emaile": "Enter your email ",
          "maile": "ex: test@gmail.com\nor +123",
          "maileerorr": "You must enter a valid email",
          "maileerorr2": "Your password must be larger than 6 characters",
          'send Password Reset link to Email':
              "send Password Reset link to Email",
          "Enter your password": "Enter your password",
          "nomaile": "Don|'t remembr password?",
          "nothaveacc": "Don|'t have an account?",
          "haveacc": "Already have an account?",
          "Back": "Back",
          "sendpass": "Send New Password",
          "categories": "categories",
          "Favorite": "favorites",
          "Account": "Account",
          "orders": "orders",
          "items": "items",
          "profile": "profile",
          "basket": "Basket",
          "homepage": "homepage",
          "must": "must",
          "popular": "popular",
          "addtobasket": "ADD to Basket",
          "MyAccount": "MyAccount",
          "Notification": "Notification",
          "HelpCenter": "Help Center",
          "Setting": "Settings",
          "LogOut": "LogOut",
          "clors": "colors",
          "BRANDS": "BRANDS",
          "find your": "find your",
          'TRACKER ORDER': "TRACKER ORDER",
          'Cart': 'Cart',
          "Address": "Address",
          'Checkout': "Checkn\nout",
          'Payment': "Payment",
          'Shipping': "Shipping",
          'Order Details': "Order Details",
          'Finish': "Finish",
          "total": "Total\n",
          "checkout": 'Checkout',
          "vouchercode": 'Add voucher code',
          "tax": "TAX",
          "order_Number": "order Number",
          "allow&Payment": "allow&Payment",
          "totalwithshapin": "The total cost of the order plus shipping costs",
          "shapemasge":
              "When the assembly of your products is completed, we will contact you in order to provide you with a tracking number for the shipping process",
          "FinishStatuse":
              "Thank you for choosing 𝓽𝓾𝓻𝓴𝓶𝓪𝓻𝓽 We wish you a pleasant shopping experience",
          "country": "country",
          "state&city ": "state&city",
          "Please enter a valid country name":
              "Please enter a valid country name",
          "Please enter a valid state&city name":
              "Please enter a valid state&city name",
          "more Address Information": " Address Information",
          "Submit": "Submit",
          "The address has been registered in the database. Thank you":
              "The address has been registered in the database. Thank you",
          "Number of products": "Number of products",
          "your number country code ex:+901":
              "country code&phone number ex:50003144",
          "phone number": "your phone ",
          "phone number error": "please enter valid phone number",
          "networkmsg": "No Internet Connection?",
          "name":"Enter your name",
          "Please enter a valid  name":"Please enter a valid  name",
          "wallet":"wallet",
          "helpcentermsg":"Your happiness is our first priority! Feel free to contact us with any questions or inquiries - we can't wait to see you soon!",
          "pname":"Name and Surname",
          "pemail":"email",
          "lang":"languages",
          "Themes":"Themes",
          "Gifts":" Gifts",
          "plase choose size":"plase choes your size",
          "please choose color":"please choose color",
          "choose country":"choose country"

        },
        "ar": {
          "lanar": 'العربية',
          "lanen": 'الانكليزبة',
          "appname": "𝓽𝓾𝓻𝓴𝓶𝓪𝓻𝓽",
          "splash1": "مرحبًا بك في 𝓽𝓾𝓻𝓴𝓶𝓪𝓻𝓽",
          "splash2": "نحن نساعد الناس على التواصل مع المتاجر \n حول تركيا",
          "splash3": "طريقة سهلة للتسوق. \n فقط تسوق معنا في المنزل",
          "Letsshop": "هيا نتسوق!",
          'Login': "تسجيل الدخول",
          "Register": 'التسجيل',
          "emaile": "أدخل بريدك الإلكتروني ",
          "maile": "ex: test@gmail.com\nor +123",
          "maileerorr": "يجب عليك إدخال بريد إلكتروني صالح",
          "Enter your password": "يرجى ادخال كلمة المرور",
          "maileerorr2": "يجب أن تكون كلمة المرور الخاصة بك أكبر من 6 أحرف",
          'send Password Reset link to Email': "ارسل كلمة مرور جديدة",
          "nomaile": "لا تذكر| كلمة المرور؟",
          "nothaveacc": "ليس لديك | حساب؟",
          "haveacc": "هل لديك حساب؟",
          "Back": "خلف",
          "sendpass": "أرسل كلمة سر جديدة",
          "categories": "الفئات",
          "Favorite": "المفضلة",
          "Account": "حسابي",
          "orders": "طلباتي",
          "items": "التصنيفات",
          "profile": "حساب تعريفي",
          "basket": "السلة",
          "homepage": "الصفحة الرئيسية",
          "popular": "الأكثر",
          "must": "شعبية",
          "addtobasket": "اضف الى السلة",
          "MyAccount": "حسابي",
          "Notification": "الإشعارات",
          "HelpCenter": "مركز المساعدة",
          "Setting": "إعدادات",
          "LogOut": "تسجيل خروج",
          "clors": "الألوان",
          "BRANDS": "العلامات التجارية",
          "find your": "ابحث عن",
          'TRACKER ORDER': "طلباتي",
          'Cart': 'التسوق',
          "Address": "العنوان",
          'Checkout': "الطلب",
          'Payment': "الدفع",
          'Shipping': "الشحن",
          'Order Details': "تفاصيل الشحنة",
          'Finish': "التسليم",
          "total": "\nالمجموع",
          "checkout": 'ارسال الطلب',
          "vouchercode": 'رمز القسيمة',
          "tax": "الضريبة ",
          "order_Number": "رقم الطلب",
          "allow&Payment": "القبول والدفع",
          "totalwithshapin":
              "التكلفة الإجمالية للطلب بالإضافة إلى تكاليف الشحن",
          "shapemasge":
              "عند اكتمال تجميع منتجاتك ، سنتصل بك لتزويدك برقم تتبع لعملية الشحن",
          "FinishStatuse": "شكرا ل اختياركم TurkMart ",
          "country": "الدولة",
          "state&city ": "مدينة &الولاية",
          "Please enter a valid country name": "الرجاء إدخال اسم دولة",
          "Please enter a valid state&city name":
              "الرجاء إدخال اسم ولاية أو مدينة صالح",
          "more Address Information": "مزيد من معلومات العنوان",
          'Submit': "إرسال",
          "The address has been registered in the database. Thank you":
              "تم تسجيل العنوان في قاعدة البيانات. شكرًا لك",
          "Number of products": "عدد المنتجات",
          "your number country code ex:+901":
              " رقم الهاتف مثال: +95000",
          "phone number": "رقم الهاتف ",
          "phone number error": "الرجاء إدخال رقم هاتف صحيح",
          "networkmsg": "يرجى فحص اتصالك بالإنترنت؟",
          "name":"أدخل أسمك",
          "Please enter a valid  name":"رجاء ادخل اسم صحيح",
          "wallet":"المحفظة",
          "helpcentermsg":"سعادتك هي أولويتنا الأولى! لا تتردد في التواصل معنا لطرح أي أسئلة أو استفسارات - فنحن متشوقون لرؤيتك قريبًا!",
          "pname":"الاسم واللقب",
          "pemail":"البريد الإلكتروني",
          "lang":"اللغات",
          "Themes":"الثيمات",
          "Gifts":"الهدايا",
          "plase choose size":"يرجى اختيار المقاس الخاص بك",
          "please choose color":"الرجاء اختيار اللون",
          "choose country":"يرجى اختيارالدولة"
          


          
        }
      };
}
